---
abstract: 'Silly Cobalt2 plugins'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cobalt-Plugin-Silly
requires:
  Cobalt::Core: 0
  Cobalt::Serializer: 0
  Object::Pluggable::Constants: 0
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
